# Generated by Django 3.2.3 on 2021-05-22 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=200, verbose_name='Apellido')),
                ('direccion', models.CharField(max_length=400, verbose_name='Dirección')),
                ('cuil', models.CharField(max_length=200, verbose_name='CUIL')),
                ('telefono', models.CharField(max_length=200, verbose_name='Telefono')),
                ('score', models.IntegerField(verbose_name='Score')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón social')),
                ('fantasia', models.CharField(max_length=200, verbose_name='Nombre de fantasia')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='Fecha del prestamo')),
                ('primera_cuota', models.DateTimeField(verbose_name='Primera cuota')),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('cuotas', models.IntegerField(verbose_name='Cuotas')),
                ('regimen', models.CharField(choices=[('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual')], max_length=20, verbose_name='Regimen')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.clientes', verbose_name='Cliente')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Prestamo',
                'verbose_name_plural': 'Prestamos',
            },
        ),
    ]
