# Generated by Django 3.2.3 on 2021-05-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cuil',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='CUIL'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono'),
        ),
    ]
