# Generated by Django 3.2.3 on 2021-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20210523_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('Rechazado', 'Rechazado'), ('Activo', 'Activo'), ('Potencial', 'Potencial'), ('cliente', 'Cliente')], default='Potencial', max_length=20, verbose_name='Estado'),
        ),
    ]
