# Generated by Django 3.2.3 on 2021-05-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_clientes_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='presupuesto_cliente',
            field=models.FloatField(blank=True, null=True, verbose_name='Presupuesto cliente'),
        ),
        migrations.AddField(
            model_name='prestamos',
            name='valor_original',
            field=models.FloatField(blank=True, null=True, verbose_name='Valor original'),
        ),
    ]
