# Generated by Django 3.2.3 on 2021-05-23 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20210523_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del prestamo')),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.prestamos', verbose_name='Prestamo')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
