# Generated by Django 3.2.3 on 2021-05-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_pagos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('Rechazado', 'Rechazado'), ('Activo', 'Activo'), ('Potencial', 'Potencial'), ('Cliente', 'Cliente'), ('Moroso', 'Moroso')], default='Potencial', max_length=20, verbose_name='Estado'),
        ),
    ]
