# Generated by Django 3.2.3 on 2021-06-14 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_clientes_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='contacto',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='empleador',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Empleador'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='fecha',
            field=models.DateField(verbose_name='Fecha del pago'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa', verbose_name='Empresa'),
        ),
    ]
