# Generated by Django 3.2.3 on 2021-06-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_clientes_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AddField(
            model_name='clientes',
            name='code_key',
            field=models.IntegerField(blank=True, null=True, verbose_name='Code key'),
        ),
    ]
