# Generated by Django 3.2.3 on 2021-06-21 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_auto_20210619_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='dni',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Dni'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='servicio',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Servicio'),
        ),
    ]
