# Generated by Django 3.2.3 on 2021-06-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_auto_20210621_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen'),
        ),
    ]
