# Generated by Django 3.2.3 on 2021-06-24 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_auto_20210623_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='adjunto',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Adjunto'),
        ),
    ]
