# Generated by Django 3.2.3 on 2021-06-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_prestamos_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamos',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Adjunto'),
        ),
    ]
