# Generated by Django 3.2.3 on 2021-07-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_alter_prestamos_adjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='informe_crediticio',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Informe crediticio'),
        ),
    ]
