# Generated by Django 3.2.3 on 2021-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_clientes_informe_crediticio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='agua_corriente',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, null=True, verbose_name='Agua corriente'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='bathrooms',
            field=models.IntegerField(blank=True, null=True, verbose_name='Baños'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cloaca',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, null=True, verbose_name='Cloaca'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='cuartos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cuartos'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='gas',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, null=True, verbose_name='Gas'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='habitantes_hogar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Habitantes del hogar'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='ingreso_hogar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ingreso hogar'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='partiente_discapacidad',
            field=models.CharField(blank=True, choices=[('SI', 'Si'), ('NO', 'No')], max_length=20, null=True, verbose_name='Pariente con discapacidad'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='titulo_vivienda',
            field=models.CharField(blank=True, choices=[('PRESTADO', 'Prestado'), ('ALQUILADO', 'Alquilado'), ('TOMADO', 'Tomado'), ('PROPIO SIN TITULO Y SIN BOLETO', 'Propio S Titulo S Boleto'), ('PROPIO CON BOLETO DE COMPRA-VENTA', 'Propio Boleto'), ('PROPIO SIN TITULO Y SIN BOLETO, CON CONSTANCIA POLICIAL', 'Propio S Titulo S Boleto Cons'), ('OTRO', 'Otro')], max_length=100, null=True, verbose_name='Vivienda'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='trabajadores_hogar',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trabajadores del hogar'),
        ),
    ]
