# Generated by Django 3.2.3 on 2021-07-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0019_auto_20210718_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='estado',
            field=models.CharField(choices=[('Potencial', 'Potencial'), ('Rechazado', 'Rechazado'), ('No activo', 'No Activo'), ('Situación 1', 'Moroso 1'), ('Situación 2', 'Moroso 2'), ('Situación 3', 'Moroso 3'), ('Situación 4', 'Moroso 4'), ('Situación 5', 'Moroso 5'), ('Situación 6', 'Moroso 6')], default='Potencial', max_length=20, verbose_name='Estado'),
        ),
    ]
