# Generated by Django 3.2.3 on 2021-08-11 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0023_cuotasprestamo_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='email',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='rubro',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Rubro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono'),
        ),
    ]
