# Generated by Django 3.2.3 on 2021-08-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0024_auto_20210811_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('final', models.DateTimeField(verbose_name='Fecha final')),
                ('asunto', models.CharField(max_length=100, verbose_name='Asunto')),
                ('descripción', models.CharField(max_length=100, verbose_name='Descripción')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
            },
        ),
    ]
