# Generated by Django 3.2.3 on 2021-10-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0026_auto_20210912_1555'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasaParaCreditos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre tasa')),
                ('valor_tasa', models.FloatField(verbose_name='Valor de la tasa')),
            ],
            options={
                'verbose_name': 'Tasa para credito',
                'verbose_name_plural': 'Tasas para creditos',
            },
        ),
    ]
