# Generated by Django 3.2.3 on 2021-10-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0027_tasaparacreditos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotasprestamo',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de pago'),
        ),
        migrations.AddField(
            model_name='cuotasprestamo',
            name='monto_bonificado',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto bonificado'),
        ),
        migrations.AddField(
            model_name='cuotasprestamo',
            name='monto_interes',
            field=models.FloatField(blank=True, null=True, verbose_name='Monto interes'),
        ),
        migrations.AlterField(
            model_name='cuotasprestamo',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de vencimiento'),
        ),
    ]
