# Generated by Django 3.2.3 on 2021-10-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0029_pagos_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuotasprestamo',
            name='monto_bonificado',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Monto bonificado'),
        ),
        migrations.AlterField(
            model_name='cuotasprestamo',
            name='monto_interes',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Monto interes'),
        ),
    ]
