# Generated by Django 3.2.3 on 2021-10-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0030_auto_20211018_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamos',
            name='entregado',
            field=models.BooleanField(default=False, verbose_name='Se entrego el material/ dinero'),
        ),
    ]
