# Generated by Django 3.2.3 on 2021-11-18 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0031_prestamos_entregado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='agua_corriente',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='bath_sit',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='bathrooms',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cloaca',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='cuartos',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='deuda',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='gas',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='habitantes_hogar',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='ingreso_hogar',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='partiente_discapacidad',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='titulo_vivienda',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='trabajadores_hogar',
        ),
    ]
