# Generated by Django 3.2.3 on 2021-11-21 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0032_auto_20211118_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='tasaparacreditos',
            unique_together={('nombre', 'valor_tasa')},
        ),
        migrations.CreateModel(
            name='ContactosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacto', models.CharField(max_length=30, verbose_name='Contacto')),
                ('numero', models.CharField(max_length=20, verbose_name='Telfono')),
                ('email', models.CharField(max_length=30, verbose_name='Email')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'unique_together': {('contacto', 'numero', 'empresa')},
            },
        ),
    ]
