# Generated by Django 3.2.3 on 2021-11-21 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0033_auto_20211121_1104'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contactosempresa',
            unique_together={('contacto', 'numero')},
        ),
    ]
