# Generated by Django 3.2.3 on 2021-11-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0034_alter_contactosempresa_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre'),
        ),
    ]
