# Generated by Django 3.2.3 on 2022-02-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0041_auto_20220109_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='cuil',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='CUIL'),
        ),
    ]
