# Generated by Django 3.2.3 on 2022-02-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0042_alter_clientes_cuil'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cuit',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='CUIL'),
        ),
    ]
