# Generated by Django 3.2.3 on 2022-02-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0044_auto_20220215_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='provincia',
        ),
        migrations.AddField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='provincia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Provincia'),
        ),
    ]
