# Generated by Django 3.2.3 on 2022-02-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0045_auto_20220215_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='CUIT'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direccion'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='provincia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Provincia'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefono'),
        ),
    ]
