# Generated by Django 3.2.3 on 2022-03-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0048_auto_20220223_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingreso', models.BooleanField(default=True)),
                ('concepto', models.CharField(default='', max_length=100, verbose_name='Concepto')),
                ('fecha', models.DateField(verbose_name='Fecha del pago')),
                ('monto', models.FloatField(verbose_name='Monto')),
            ],
            options={
                'verbose_name': 'Movimiento contable',
                'verbose_name_plural': 'Movimientos contables',
            },
        ),
        migrations.AddField(
            model_name='prestamos',
            name='valor_actual_ar',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Valor actual antes de refinanciar'),
        ),
    ]
