# Generated by Django 3.2.3 on 2022-03-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0049_auto_20220323_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientocontable',
            name='cuenta',
            field=models.CharField(default='', max_length=100, verbose_name='Cuenta'),
        ),
    ]
