# Generated by Django 3.2.3 on 2022-04-01 11:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0051_logsacciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='logsacciones',
            name='dia',
            field=models.DateField(default=datetime.date(2022, 4, 1), verbose_name='Dia'),
        ),
    ]
